addSbtPlugin("dev.guardrail"    % "sbt-guardrail"       % "0.70.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.6")
//addSbtPlugin("com.dwijnand"     % "sbt-dynver"          % "3.1.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "1.2.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.0")
